// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClXttdfv6Y0mpLZYTmGSJ_W9SbX5rmSvw',
    appId: '1:212850643110:web:ee5a3ed5406c896a9a6467',
    messagingSenderId: '212850643110',
    projectId: 'enwawi-8cdd0',
    authDomain: 'enwawi-8cdd0.firebaseapp.com',
    storageBucket: 'enwawi-8cdd0.appspot.com',
    measurementId: 'G-1ZD6BCKZTK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjp3aNyh2zF-dTDxYEy4HD_KG1tB68gDg',
    appId: '1:212850643110:android:e59105d88cec39b59a6467',
    messagingSenderId: '212850643110',
    projectId: 'enwawi-8cdd0',
    storageBucket: 'enwawi-8cdd0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhadkomN72k5AVfuPMYJQXt5BBr3cOiZA',
    appId: '1:212850643110:ios:630c838a2b028cb99a6467',
    messagingSenderId: '212850643110',
    projectId: 'enwawi-8cdd0',
    storageBucket: 'enwawi-8cdd0.appspot.com',
    iosBundleId: 'com.example.agri',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhadkomN72k5AVfuPMYJQXt5BBr3cOiZA',
    appId: '1:212850643110:ios:efecf3293a2ad7cc9a6467',
    messagingSenderId: '212850643110',
    projectId: 'enwawi-8cdd0',
    storageBucket: 'enwawi-8cdd0.appspot.com',
    iosBundleId: 'com.example.agri.RunnerTests',
  );
}
